<?php
/**
 * Created by PhpStorm.
 * User: Dwi Randy H
 * Date: 5/2/2019
 * Time: 12:40 PM
 */

namespace App\Http\Controllers\Evaluator;

use App\Http\Controllers\Administrator\BaseController;
use App\Repositories\DetailPenilaianRepository;
use App\Repositories\PenilaianRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class PenilaianController extends BaseController
{
    private $penilaianRepo, $detailPenilaianRepo;

    function __construct(PenilaianRepository $penilaianRepository, DetailPenilaianRepository $detailPenilaianRepository)
    {
        $this->title = 'Penilaian LKE';
        $this->repository = $penilaianRepository;
        $this->route = '/evaluator/penilaian';
        $this->view = 'evaluator.penilaian.data';

        $this->penilaianRepo = $penilaianRepository;
        $this->detailPenilaianRepo = $detailPenilaianRepository;

        parent::__construct();
    }

    public function index(Request $request)
    {
        $this->viewData['jabatan'] = Auth::guard('evaluator')->user()->jabatan;
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    public function add()
    {
        $this->viewData['nilaiYT'] = \Config::get('custom.nilaiYT');
        $this->viewData['nilaiAbjad'] = \Config::get('custom.nilaiAbjad');

        $this->view = 'penilaian.tambah';
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public function evaluasiForm(Request $request, $id){
        $this->viewData['nilaiYT'] = \Config::get('custom.nilaiYT');
        $this->viewData['nilaiAbjad'] = \Config::get('custom.nilaiAbjad');

        $this->view = 'penilaian.tambah';

        $this->viewData['penilaian'] = $this->penilaianRepo->detail($id);

        $this->viewData['detailPenilaian'] = $this->penilaianRepo->getDetailPenilaianById($id);

        return view('evaluator.penilaian.submit', $this->viewData);
    }

    public function submitEvaluasi(Request $request, $id){
        $data['nilai_akhir'] = $request->post('nilai_akhir');
        $data['nilai_A_persentase'] = $request->post('nilai_A_persentase');
        $data['nilai_A'] = $request->post('nilai_A');
        $data['nilai_A_I_persentase'] = $request->post('nilai_A_I_persentase');
        $data['nilai_A_I'] = $request->post('nilai_A_I');
        $data['nilai_A_I_a_persentase'] = $request->post('nilai_A_I_a_persentase');
        $data['nilai_A_I_a'] = $request->post('nilai_A_I_a');
        $data['nilai_A_I_b_persentase'] = $request->post('nilai_A_I_b_persentase');
        $data['nilai_A_I_b'] = $request->post('nilai_A_I_b');
        $data['nilai_A_I_c_persentase'] = $request->post('nilai_A_I_c_persentase');
        $data['nilai_A_I_c'] = $request->post('nilai_A_I_c');
        $data['nilai_A_II_persentase'] = $request->post('nilai_A_II_persentase');
        $data['nilai_A_II'] = $request->post('nilai_A_II');
        $data['nilai_A_II_a_persentase'] = $request->post('nilai_A_II_a_persentase');
        $data['nilai_A_II_a'] = $request->post('nilai_A_II_a');
        $data['nilai_A_II_b_persentase'] = $request->post('nilai_A_II_b_persentase');
        $data['nilai_A_II_b'] = $request->post('nilai_A_II_b');
        $data['nilai_A_II_c_persentase'] = $request->post('nilai_A_II_c_persentase');
        $data['nilai_A_II_c'] = $request->post('nilai_A_II_c');
        $data['nilai_B_persentase'] = $request->post('nilai_B_persentase');
        $data['nilai_B'] = $request->post('nilai_B');
        $data['nilai_B_I_persentase'] = $request->post('nilai_B_I_persentase');
        $data['nilai_B_I'] = $request->post('nilai_B_I');
        $data['nilai_B_II_persentase'] = $request->post('nilai_B_II_persentase');
        $data['nilai_B_II'] = $request->post('nilai_B_II');
        $data['nilai_B_III_persentase'] = $request->post('nilai_B_III_persentase');
        $data['nilai_B_III'] = $request->post('nilai_B_III');
        $data['nilai_C_persentase'] = $request->post('nilai_C_persentase');
        $data['nilai_C'] = $request->post('nilai_C');
        $data['nilai_C_I_persentase'] = $request->post('nilai_C_I_persentase');
        $data['nilai_C_I'] = $request->post('nilai_C_I');
        $data['nilai_C_II_persentase'] = $request->post('nilai_C_II_persentase');
        $data['nilai_C_II'] = $request->post('nilai_C_II');
        $data['nilai_C_III_persentase'] = $request->post('nilai_C_III_persentase');
        $data['nilai_C_III'] = $request->post('nilai_C_III');
        $data['nilai_D_persentase'] = $request->post('nilai_D_persentase');
        $data['nilai_D'] = $request->post('nilai_D');
        $data['nilai_D_I_persentase'] = $request->post('nilai_D_I_persentase');
        $data['nilai_D_I'] = $request->post('nilai_D_I');
        $data['nilai_D_II_persentase'] = $request->post('nilai_D_II_persentase');
        $data['nilai_D_II'] = $request->post('nilai_D_II');
        $data['nilai_D_III_persentase'] = $request->post('nilai_D_III_persentase');
        $data['nilai_D_III'] = $request->post('nilai_D_III');
        $data['nilai_E_persentase'] = $request->post('nilai_E_persentase');
        $data['nilai_E'] = $request->post('nilai_E');
        $data['nilai_E_I_persentase'] = $request->post('nilai_E_I_persentase');
        $data['nilai_E_I'] = $request->post('nilai_E_I');
        $data['nilai_E_II_persentase'] = $request->post('nilai_E_II_persentase');
        $data['nilai_E_II'] = $request->post('nilai_E_II');
        $data['status'] = 'sementara';
        $this->penilaianRepo->update($data, $id);


        // form kriteria penilaian
        $kriteria = $request->post('kriteria');
        foreach ($kriteria as $key => $row){
            if (isset($row['idDetail'])){
                if (isset($row['pilihan'])){
                    $detail['pilihan'] = $row['pilihan'];
                }
                $detail['nilai'] = $row['nilai'];
                $detail['catatan_evaluator'] = $row['catatan_evaluator'];
                $this->detailPenilaianRepo->update($detail, $row['idDetail']);
            }
        }


        return redirect('/evaluator/penilaian');
    }
}