<?php
/**
 * Created by PhpStorm.
 * User: Dwi Randy H
 * Date: 5/2/2019
 * Time: 12:40 PM
 */

namespace App\Http\Controllers\Administrator\SatuanKerja;

use App\Http\Controllers\Administrator\BaseController;
use App\Repositories\PetugasSatkerRepository;
use App\Repositories\SatuanKerjaRepository;
use Illuminate\Http\Request;

class PetugasController extends BaseController
{
    private $satuanKerjaRepo;

    function __construct(PetugasSatkerRepository $petugasSatkerRepository, SatuanKerjaRepository $satuanKerjaRepository)
    {
        $this->title = 'Petugas Satuan Kerja';
        $this->repository = $petugasSatkerRepository;
        $this->route = '/administrator/satuan-kerja/petugas';
        $this->view = 'administrator.satuan_kerja.petugas';
        $this->input = [
            'id_satuan_kerja' => [
                'rule' => 'required'
            ],
            'nama' => [
                'rule' => 'required'
            ],
            'jabatan' => [
                'rule' => 'required',
            ],
            'email' => [
                'rule' => 'required',
            ],
            'password' => [
                'rule' => 'required',
            ]
        ];

        $this->satuanKerjaRepo = $satuanKerjaRepository;
        parent::__construct();
    }

    public function add()
    {
        $this->viewData['satuanKerja'] = $this->satuanKerjaRepo->getDataDropdown();
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public function store(Request $request)
    {
        $request->merge(['password' => bcrypt($request->post('password'))]);
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    public function edit($id)
    {
        $this->viewData['satuanKerja'] = $this->satuanKerjaRepo->getDataDropdown();
        return parent::edit($id); // TODO: Change the autogenerated stub
    }

    public function update(Request $request, $id)
    {
        unset($this->input['password']);

        $request->merge(['password' => bcrypt($request->post('password'))]);

        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }
}